<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pablo Araya Gajardo">
<meta name="keywords" content="Juventud, Salud Mental, Empleo, Precariedad Laboral, ENJUV, Chile">

<title>Análisis de la Salud Mental y su Relación con la Situación Laboral en Juventudes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analisis-salud-mental-enjuv-chile_files/libs/clipboard/clipboard.min.js"></script>
<script src="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/popper.min.js"></script>
<script src="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/anchor.min.js"></script>
<link href="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analisis-salud-mental-enjuv-chile_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analisis-salud-mental-enjuv-chile_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analisis-salud-mental-enjuv-chile_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analisis-salud-mental-enjuv-chile_files/libs/bootstrap/bootstrap-f0453fa9a0fb9e31abb91c0e094c702e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="analisis-salud-mental-enjuv-chile_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="analisis-salud-mental-enjuv-chile_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice de Contenidos</h2>
   
  <ul>
  <li><a href="#objetivo-del-análisis" id="toc-objetivo-del-análisis" class="nav-link active" data-scroll-target="#objetivo-del-análisis"><span class="header-section-number">1</span> Objetivo del análisis</a></li>
  <li><a href="#metodología-de-análisis" id="toc-metodología-de-análisis" class="nav-link" data-scroll-target="#metodología-de-análisis"><span class="header-section-number">2</span> Metodología de análisis</a></li>
  <li><a href="#principales-hallazgos" id="toc-principales-hallazgos" class="nav-link" data-scroll-target="#principales-hallazgos"><span class="header-section-number">3</span> Principales hallazgos</a>
  <ul class="collapse">
  <li><a href="#análisis-del-índice-de-malestar-psicológico-e-índice-de-acceso-a-atención" id="toc-análisis-del-índice-de-malestar-psicológico-e-índice-de-acceso-a-atención" class="nav-link" data-scroll-target="#análisis-del-índice-de-malestar-psicológico-e-índice-de-acceso-a-atención"><span class="header-section-number">3.1</span> Análisis del Índice de Malestar Psicológico e Índice de Acceso a Atención</a></li>
  <li><a href="#cómo-se-distribuye-el-malestar-psicológico" id="toc-cómo-se-distribuye-el-malestar-psicológico" class="nav-link" data-scroll-target="#cómo-se-distribuye-el-malestar-psicológico"><span class="header-section-number">3.2</span> ¿Cómo se distribuye el malestar psicológico?</a></li>
  <li><a href="#cómo-se-distribuye-la-percepción-al-acceso-a-la-atencion-psicológica" id="toc-cómo-se-distribuye-la-percepción-al-acceso-a-la-atencion-psicológica" class="nav-link" data-scroll-target="#cómo-se-distribuye-la-percepción-al-acceso-a-la-atencion-psicológica"><span class="header-section-number">3.3</span> ¿Cómo se distribuye la percepción al acceso a la atencion psicológica?</a></li>
  <li><a href="#cuál-es-la-relación-entre-el-malestar-psicológico-y-el-acceso-percibido" id="toc-cuál-es-la-relación-entre-el-malestar-psicológico-y-el-acceso-percibido" class="nav-link" data-scroll-target="#cuál-es-la-relación-entre-el-malestar-psicológico-y-el-acceso-percibido"><span class="header-section-number">3.4</span> ¿Cuál es la relación entre el malestar psicológico y el acceso percibido?</a></li>
  <li><a href="#análisis-inferencial" id="toc-análisis-inferencial" class="nav-link" data-scroll-target="#análisis-inferencial"><span class="header-section-number">3.5</span> Análisis Inferencial</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">4</span> Conclusiones</a></li>
  <li><a href="#fuentes-consultadas" id="toc-fuentes-consultadas" class="nav-link" data-scroll-target="#fuentes-consultadas"><span class="header-section-number">5</span> Fuentes consultadas</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="analisis-salud-mental-enjuv-chile.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Análisis de la Salud Mental y su Relación con la Situación Laboral en Juventudes</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Pablo Araya Gajardo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">9 de agosto de 2025</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    <p>El presente estudio analiza la relación entre la situación laboral y la salud mental en jóvenes de Chile, con el objetivo de explorar, desde una perspectiva crítica, las diferencias en malestar psicológico y acceso percibido a la atención. Utilizando los datos de la 10ma Encuesta Nacional de Juventudes (ENJUV), se aplicó una metodología cuantitativa en R y RStudio. Se construyeron dos indicadores principales: un Índice de Malestar Psicológico y un Índice de Acceso a Atención. El análisis incluyó estadísticas descriptivas, pruebas de hipótesis (t-Student) y diversas visualizaciones de datos para comparar a los jóvenes ocupados versus los desocupados o inactivos. Los resultados confirman que el grupo de jóvenes sin ocupación reporta niveles de malestar psicológico significativamente más altos. Sin embargo, este mismo grupo percibe un acceso significativamente mayor a la atención en salud mental que sus pares empleados. Adicionalmente, se encontró una correlación positiva donde, a mayor malestar, mayor es el acceso percibido, refutando una posible “doble vulnerabilidad”. Se concluye que, si bien la falta de empleo es un factor de riesgo para el bienestar psicológico, la empleabilidad por sí sola no garantiza ni el acceso ni la percepción de seguridad para afrontar los costos de la salud mental. Se postula que la precariedad de los trabajos juveniles podría explicar esta brecha, subrayando la necesidad de que las políticas públicas se enfoquen no solo en la creación de empleo, sino también en la calidad y seguridad de este para asegurar un desarrollo integral de las juventudes.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Palabras clave</div>
    <p>Juventud, Salud Mental, Empleo, Precariedad Laboral, ENJUV, Chile</p>
  </div>
</div>

</header>


<section id="objetivo-del-análisis" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-del-análisis"><span class="header-section-number">1</span> Objetivo del análisis</h2>
<p>El objetivo de este trabajo es analizar la relación entre la situación laboral (empleo y desempleo) y la salud mental en las juventudes de Chile, utilizando los datos de la 10ma Encuesta Nacional de Juventudes (ENJUV) 2022. Se busca explorar si existen diferencias significativas en los indicadores de bienestar psicológico entre jóvenes empleados y desempleados, y analizar estos resultados desde una perspectiva crítica que considere las condiciones del mercado laboral juvenil en el país.</p>
</section>
<section id="metodología-de-análisis" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="metodología-de-análisis"><span class="header-section-number">2</span> Metodología de análisis</h2>
<p>El presente estudio corresponde a un análisis cuantitativo, descriptivo y correlacional, implementado a través del software R (versión 4.5.0) y el entorno de desarrollo RStudio. Se utilizó principalmente el conjunto de librerías del tidyverse, con especial énfasis en dplyr para la manipulación de datos y ggplot2 para la visualización.</p>
<p><strong>Fuente de Datos y Muestra</strong></p>
<p>La fuente de datos principal es la base de la 10ma Encuesta Nacional de Juventudes (ENJUV), realizada por el Instituto Nacional de la Juventud (INJUV) de Chile en el año 2022. Esta encuesta es representativa a nivel nacional y regional para la población de entre 15 y 29 años.</p>
<p><strong>Operacionalización y Construcción de Variables</strong></p>
<p>Para abordar los objetivos del estudio, se seleccionaron y construyeron las siguientes variables clave a partir de la base de datos original:</p>
<p><strong>1. Variable Independiente: Situación Laboral.</strong> Se creó una variable categórica y dicotómica a partir de las preguntas P36, P37 y P38, que indagan sobre el trabajo remunerado. Se definió como “Ocupado/a” a todo joven que respondió “1. Sí” a cualquiera de estas tres preguntas. Todos los demás casos fueron agrupados en la categoría “Desocupado/a o Inactivo/a”.</p>
<p><strong>2. Índice de Malestar Psicológico.</strong> Se construyó un índice sumatorio para medir sintomatología ansiosa-depresiva. Se utilizaron las variables P102_1 a P102_7, que consultan la frecuencia de sentimientos como nerviosismo, preocupación, desánimo, anhedonia, problemas de sueño, soledad e ideación suicida. Las respuestas originales en formato de texto (“Para nada”, “Varios días”, “Más de la mitad de los días” y “Casi todos los días”) fueron recodificadas a una escala numérica del 1 al 4. El Índice de Malestar Psicológico corresponde a la suma de estos puntajes, generando un rango teórico de 7 (mínimo malestar) a 28 (máximo malestar).</p>
<p><strong>3. Índice de Acceso a Atención.</strong> Para medir la percepción sobre la posibilidad de costear servicios de salud mental, se creó un segundo índice sumatorio. Se utilizaron las variables P105_1, P105_2 y P105_3, que evalúan la posibilidad de costear consultas, medicamentos y exámenes. Sus respuestas textuales (“Nada posible”, “Poco posible”, “Algo posible” y “Muy posible”) también fueron recodificadas a una escala numérica del 1 al 4. El Índice de Acceso a Atención Psicológica es la suma de estos valores, con un rango teórico de 3 (mínimo acceso percibido) a 12 (máximo acceso percibido).</p>
<p>&nbsp;</p>
<p><strong>Técnicas de Análisis</strong></p>
<p>El flujo de trabajo analítico siguió los siguientes pasos:</p>
<ul>
<li><p>Análisis Descriptivo: Se calcularon estadísticas de tendencia central (media, mediana) y de dispersión (desviación estándar) para los dos índices construidos, agrupando los resultados por la variable de Situación Laboral para realizar una primera comparación de los grupos.</p></li>
<li><p>Visualización de Hallazgos: Se empleó la librería ggplot2 para generar tres tipos de visualizaciones con el fin de explorar las relaciones y distribuciones:</p>
<ul>
<li><p>Gráficos de densidad para comparar la forma completa de la distribución de ambos índices entre los dos grupos.</p></li>
<li><p>Diagramas de cajas (Boxplots) para obtener un resumen visual de las medianas, rangos intercuartílicos y la dispersión de los datos.</p></li>
<li><p>Diagrama de dispersión (Scatter plot) con líneas de tendencia por grupo, para investigar la correlación entre el malestar psicológico y el acceso percibido.</p></li>
</ul></li>
<li><p>Análisis Inferencial: Se aplicaron dos tipos de pruebas de hipótesis para evaluar estadísticamente los hallazgos. Primero, para determinar si las diferencias observadas en las medias de los índices entre los grupos “Ocupado/a” y “Desocupado/a o Inactivo/a” eran significativas, se aplicó la prueba t de Student para muestras independientes, utilizando la corrección de Welch que R implementa por defecto. Segundo, para cuantificar la fuerza y dirección de la relación entre las dos variables numéricas (Índice de Malestar e Índice de Acceso), se realizó una prueba de correlación de Pearson. Para todas las pruebas se utilizó un nivel de significancia (alfa) de 0.05.</p></li>
</ul>
</section>
<section id="principales-hallazgos" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="principales-hallazgos"><span class="header-section-number">3</span> Principales hallazgos</h2>
<section id="análisis-del-índice-de-malestar-psicológico-e-índice-de-acceso-a-atención" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="análisis-del-índice-de-malestar-psicológico-e-índice-de-acceso-a-atención"><span class="header-section-number">3.1</span> Análisis del Índice de Malestar Psicológico e Índice de Acceso a Atención</h3>
<div class="cell" data-tbl-cap="Estadísticas Descriptivas de los Índices por Situación Laboral" data-tbl-pos="H">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Estadísticas Descriptivas de los Índices por Situación Laboral</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Situación Laboral</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media Malestar</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mediana Malestar</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">DE Malestar</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media Acceso</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mediana Acceso</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DE Acceso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em;">Desocupado/a o Inactivo/a</td>
<td style="text-align: center;">4596</td>
<td style="text-align: center;">12.1</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6.9</td>
<td style="text-align: center;">7</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em;">Ocupado/a</td>
<td style="text-align: center;">5104</td>
<td style="text-align: center;">11.5</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">6</td>
<td style="text-align: left;">3.5</td>
</tr>
</tbody>
</table>
</div>
<p>La tabla 3.1 revela dos hallazgos centrales. Primero, en relación con el malestar psicológico, se observa que el <strong>promedio de malestar es levemente superior en el grupo de jóvenes desocupados o inactivos</strong> (Media = 12.1) frente a los ocupados (Media = 11.5). Sin embargo, la mediana de malestar es idéntica para ambos grupos (Mediana = 11), lo que sugiere que la diferencia en el promedio podría ser impulsada por un subconjunto de jóvenes desocupados con niveles de malestar particularmente elevados, más que por una tendencia generalizada.</p>
<p>El segundo hallazgo, se refiere al acceso a la atención. Contrario a lo que se podría esperar, el <strong>grupo de desocupados o inactivos reporta una percepción de acceso a servicios de salud mental ligeramente superior</strong> (Media = 6.9, Mediana = 7) que el grupo de jóvenes ocupados (Media = 6.5, Mediana = 6).</p>
</section>
<section id="cómo-se-distribuye-el-malestar-psicológico" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="cómo-se-distribuye-el-malestar-psicológico"><span class="header-section-number">3.2</span> ¿Cómo se distribuye el malestar psicológico?</h3>
<div class="cell" data-tbl-pos="H">
<div class="cell-output-display">
<div id="fig-densidad-malestar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-densidad-malestar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analisis-salud-mental-enjuv-chile_files/figure-html/fig-densidad-malestar-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-densidad-malestar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Distribución del Malestar Psicológico en Jóvenes según Situación Laboral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>El gráfico de densidad (Ver Gráfico 3.1) revela que la distribución es bimodal, con un pico agudo en la zona de bajo malestar (puntaje = 8) y una meseta en la zona de malestar medio-alto.</p>
<p>Al comparar los grupos se puede observar que en los niveles bajos y medios de malestar las distribuciones para jóvenes ocupados y desocupados/inactivos son notablemente similares. También se observa una diferencia clave en la cola derecha de la distribución. A partir de un puntaje de 15, el grupo de desocupados/inactivos (en rojo) presenta una densidad consistentemente mayor, lo que indica que una proporción más alta de este grupo se concentra en los niveles más elevados de malestar psicológico.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-malestar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-malestar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analisis-salud-mental-enjuv-chile_files/figure-html/fig-boxplot-malestar-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-malestar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Comparación del Malestar Psicológico por Situación Laboral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A través del diagrama de cajas (Ver Gráfico 3.2), que compara el Índice de Malestar Psicológico entre ambos grupos, se visualiza la <strong>identidad de las medianas</strong>. Tanto para el grupo de jóvenes ocupados como para el de desocupados o inactivos, la mediana está en el valor 11. Esto indica que el 50% central de la muestra en ambos grupos experimenta niveles de malestar muy similares.</p>
<p>El gráfico de cajas, por lo tanto, confirma que la diferencia proviene de una mayor concentración de casos con alto malestar en la cola de la distribución del grupo de desocupados.</p>
</section>
<section id="cómo-se-distribuye-la-percepción-al-acceso-a-la-atencion-psicológica" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="cómo-se-distribuye-la-percepción-al-acceso-a-la-atencion-psicológica"><span class="header-section-number">3.3</span> ¿Cómo se distribuye la percepción al acceso a la atencion psicológica?</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-densidad-atencion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-densidad-atencion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analisis-salud-mental-enjuv-chile_files/figure-html/fig-densidad-atencion-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-densidad-atencion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Distribución del Acceso a Atención Psicológica en Jóvenes según Situación Laboral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>El Gráfico 3.3 presenta la distribución del Índice de Acceso a Atención Psicológica. La distribución es marcadamente <strong>multimodal</strong> , con picos en los puntajes que corresponden a respuestas consistentes de “Nada posible” (3), “Poco posible” (6), “Algo posible” (9) y “Muy posible” (12).</p>
<p>La comparación entre los grupos por situación laboral revela un patrón <strong>inverso</strong>. En los niveles bajos de acceso percibido (picos en 3 y 6), la densidad es ligeramente mayor para el grupo de jóvenes ocupados. Por el contrario, en los niveles altos de acceso (picos en 9 y 12), la densidad del grupo de desocupados o inactivos es visiblemente superior.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-atencion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-atencion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analisis-salud-mental-enjuv-chile_files/figure-html/fig-boxplot-atencion-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-atencion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Comparación del Acceso a Atención Psicológica por Situación Laboral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>El diagrama de cajas (Ver Gráfico 3.4) permite ver que la mediana del Índice de Acceso a Atención Psicológica es superior para el grupo de jóvenes desocupados o inactivos (Mediana = 7) en comparación con el grupo de jóvenes ocupados (Mediana = 6).</p>
<p>Este resultado confirma que el joven típico sin una ocupación laboral percibe que costear la atención es más posible que su contraparte empleada. Si bien el rango de respuestas es similar para ambos grupos, la tendencia central está claramente desplazada.</p>
</section>
<section id="cuál-es-la-relación-entre-el-malestar-psicológico-y-el-acceso-percibido" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="cuál-es-la-relación-entre-el-malestar-psicológico-y-el-acceso-percibido"><span class="header-section-number">3.4</span> ¿Cuál es la relación entre el malestar psicológico y el acceso percibido?</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagrama-indices" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagrama-indices-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analisis-salud-mental-enjuv-chile_files/figure-html/fig-diagrama-indices-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagrama-indices-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Relación entre el malestar psicológico y el acceso percibido.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Finalmente, para explorar la interacción entre el malestar y el acceso, se generó un diagrama de dispersión con líneas de tendencia por grupo (Ver Gráfico 3.5). Este gráfico revela dos patrones significativos.</p>
<p>Primero, se observa una correlación positiva entre el malestar psicológico y el acceso percibido para ambos grupos. Las líneas de tendencia ascendentes indican que los jóvenes que reportan un mayor malestar también tienden a reportar una mayor posibilidad de costear la atención.</p>
<p>Segundo, el gráfico confirma que existe una brecha sistemática entre los grupos. Para cualquier nivel de malestar, la línea de tendencia del grupo de desocupados/inactivos se sitúa por encima de la del grupo de ocupados, reafirmando que su percepción de acceso es consistentemente superior.</p>
</section>
<section id="análisis-inferencial" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="análisis-inferencial"><span class="header-section-number">3.5</span> Análisis Inferencial</h3>
<div class="cell" data-tbl-cap="Resultados de las Pruebas t de Student para la Diferencia de Medias. Nota: gl = Grados de Libertad; IC = Intervalo de Confianza.">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Resultados de las Pruebas t de Student para la Diferencia de Medias. Nota: gl = Grados de Libertad; IC = Intervalo de Confianza.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Índice Analizado</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Estadístico t (gl)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Valor p</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">IC 95% para la Diferencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">Malestar Psicológico</td>
<td style="text-align: center;">4.35 (9598.08)</td>
<td style="text-align: center;">1.4e-05</td>
<td style="text-align: center;">[0.29, 0.77]</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Acceso a Atención</td>
<td style="text-align: center;">6.34 (9582.11)</td>
<td style="text-align: center;">2.34e-10</td>
<td style="text-align: center;">[0.31, 0.59]</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como se observa en la Tabla 3.2, los resultados de las pruebas t de Student confirman que las diferencias observadas entre los grupos “Ocupado/a” y “Desocupado/a o Inactivo/a” son estadísticamente significativas para ambos índices.</p>
<p>Para el Índice de Malestar Psicológico, el valor p (p &lt; .001) nos permite rechazar la hipótesis nula, confirmando que los jóvenes sin ocupación laboral presentan, en promedio, un malestar mayor. De manera aún más marcada, la prueba para el Índice de Acceso a Atención también arroja un resultado altamente significativo (p &lt; .001), validando estadísticamente el hallazgo paradójico de que el grupo de desocupados/inactivos reporta una percepción de acceso superior.</p>
<div class="cell" data-tbl-cap="Prueba de Correlación de Pearson entre Malestar Psicológico y Acceso a Atención" data-tbl-pos="H">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prueba de Correlación de Pearson entre Malestar Psicológico y Acceso a Atención</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 29%">
<col style="width: 23%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variables Analizadas</th>
<th style="text-align: center;">Coeficiente de Correlación (r)</th>
<th style="text-align: center;">Grados de Libertad (gl)</th>
<th style="text-align: center;">Valor p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Malestar Psicológico y Acceso a Atención</td>
<td style="text-align: center;">0.31</td>
<td style="text-align: center;">9698</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A su vez, para cuantificar la relación observada en el diagrama de dispersión entre el malestar psicológico y el acceso percibido, se realizó una prueba de correlación de Pearson.</p>
<p>Los resultados revelan una correlación positiva, aunque moderada, que es estadísticamente muy significativa (cor = .31, p &lt; .001). Esto indica que a medida que aumenta el Índice de Malestar Psicológico, también tiende a aumentar el Índice de Acceso a Atención. El hallazgo respalda la hipótesis de que la necesidad de atención puede generar una mayor conciencia de las vías de acceso disponibles.</p>
</section>
</section>
<section id="conclusiones" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">4</span> Conclusiones</h2>
<p>El presente análisis sobre la relación entre situación laboral y salud mental en las juventudes chilenas, basado en la 10ma ENJUV, revela un panorama complejo y lleno de matices. Si bien se confirma que el grupo “Desocupado/a” presentan mayores indices de malestar psicológico, los hallazgos en torno al acceso a la atención y la interacción entre variables pintan un cuadro que requiere una interpretación crítica.</p>
<p>En primer lugar, el análisis corrobora que la falta de ocupación laboral está asociada a un mayor detrimento de la salud mental. Aunque la experiencia de malestar más común es similar para todos los jóvenes, la vulnerabilidad a sufrir niveles de angustia más severos es significativamente mayor en el grupo que no tiene una ocupación. Como demostró el análisis de distribución, es esta mayor concentración de casos en los extremos más agudos del malestar lo que impulsa la diferencia estadísticamente significativa entre las medias, confirmando que la inactividad o el desempleo representan un factor de riesgo para el bienestar psicológico.</p>
<p>Sin embargo, el hallazgo más interesante surge al analizar la percepción de acceso a la atención. Contrario a lo que se podría esperar, tener un empleo no se traduce en una mejor percepción de acceso a los servicios de salud mental; de hecho, la tendencia es significativamente opuesta. Esta aparente contradicción podría explicarse por la precariedad del mercado laboral juvenil. Es plausible que muchos empleos ofrezcan bajos salarios y carezcan de seguros de salud robustos, generando una percepción de que los ingresos son insuficientes para costear un tratamiento. Por otro lado, jóvenes inactivos (como estudiantes) o desocupados podrían tener mayor conciencia de su cobertura a través de sistemas públicos como FONASA o de seguros familiares, lo que, a pesar de otras barreras, eleva su percepción de poder acceder a atenderse.</p>
<p>Finalmente, el análisis de la relación directa entre malestar y acceso añade una capa más de complejidad, mostrando una correlación positiva: a mayor malestar, mayor es el acceso percibido. Esto sugiere que la propia necesidad de atención podría actuar como un motor para que los jóvenes tomen conciencia de las vías de acceso que, de otro modo, no habrían explorado.</p>
<p>En resumen, este trabajo concluye que, si bien la falta de ocupación es un factor de vulnerabilidad para la salud mental, el mero hecho de tener un empleo no garantiza ni el bienestar ni el acceso a los medios para procurarlo. Las condiciones de la empleabilidad juvenil emergen como un factor crítico que merece un análisis más profundo, sugiriendo que las políticas públicas deben enfocarse no solo en la creación de puestos de trabajo, sino también en la calidad y la seguridad que estos ofrecen para asegurar un desarrollo integral de las juventudes.</p>
</section>
<section id="fuentes-consultadas" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="fuentes-consultadas"><span class="header-section-number">5</span> Fuentes consultadas</h2>
<p>Instituto Nacional de la Juventud (INJUV). (2022). 10ma Encuesta Nacional de Juventudes. Santiago, Chile. <a href="https://www.injuv.gob.cl/encuestanacionaldejuventud" class="uri">https://www.injuv.gob.cl/encuestanacionaldejuventud</a>.</p>
<p>Fundación SOL. (2025). Escuela de Datos 2025. <a href="https://aulavirtual.escuelasol.cl/escuela-de-datos" class="uri">https://aulavirtual.escuelasol.cl/escuela-de-datos</a></p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Análisis de la Salud Mental y su Relación con la Situación Laboral en Juventudes"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Pablo Araya Gajardo"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 08-09-2025</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">abstract:</span><span class="co"> |</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  El presente estudio analiza la relación entre la situación laboral y la salud mental en jóvenes de Chile, con el objetivo de explorar, desde una perspectiva crítica, las diferencias en malestar psicológico y acceso percibido a la atención. Utilizando los datos de la 10ma Encuesta Nacional de Juventudes (ENJUV), se aplicó una metodología cuantitativa en R y RStudio. Se construyeron dos indicadores principales: un Índice de Malestar Psicológico y un Índice de Acceso a Atención. El análisis incluyó estadísticas descriptivas, pruebas de hipótesis (t-Student) y diversas visualizaciones de datos para comparar a los jóvenes ocupados versus los desocupados o inactivos. Los resultados confirman que el grupo de jóvenes sin ocupación reporta niveles de malestar psicológico significativamente más altos. Sin embargo, este mismo grupo percibe un acceso significativamente mayor a la atención en salud mental que sus pares empleados. Adicionalmente, se encontró una correlación positiva donde, a mayor malestar, mayor es el acceso percibido, refutando una posible "doble vulnerabilidad". Se concluye que, si bien la falta de empleo es un factor de riesgo para el bienestar psicológico, la empleabilidad por sí sola no garantiza ni el acceso ni la percepción de seguridad para afrontar los costos de la salud mental. Se postula que la precariedad de los trabajos juveniles podría explicar esta brecha, subrayando la necesidad de que las políticas públicas se enfoquen no solo en la creación de empleo, sino también en la calidad y seguridad de este para asegurar un desarrollo integral de las juventudes.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">keywords:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">  - Juventud</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">  - Salud Mental</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">  - Empleo</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">  - Precariedad Laboral</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">  - ENJUV</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - Chile</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">language:</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">  crossrefs:</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-title: "Gráfico"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">    chapter-title: "Capítulo"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">    echo: False</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: litera</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Índice de Contenidos"</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">    documentclass: report</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">    papersize: a4</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-left: 2.5cm</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-right: 2.5cm</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Índice de Contenidos"</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">    latex-engine: xelatex</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">    include-in-header:</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co">      - text: |</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co">          \usepackage{float}</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co">          \usepackage{caption}</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co">          \renewcommand{\abstractname}{Resumen}</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="co">          \renewcommand{\chaptername}{Capítulo}</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo del análisis</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>El objetivo de este trabajo es analizar la relación entre la situación laboral (empleo y desempleo) y la salud mental en las juventudes de Chile, utilizando los datos de la 10ma Encuesta Nacional de Juventudes (ENJUV) 2022. Se busca explorar si existen diferencias significativas en los indicadores de bienestar psicológico entre jóvenes empleados y desempleados, y analizar estos resultados desde una perspectiva crítica que considere las condiciones del mercado laboral juvenil en el país.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Metodología de análisis</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>El presente estudio corresponde a un análisis cuantitativo, descriptivo y correlacional, implementado a través del software R (versión 4.5.0) y el entorno de desarrollo RStudio. Se utilizó principalmente el conjunto de librerías del tidyverse, con especial énfasis en dplyr para la manipulación de datos y ggplot2 para la visualización.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>**Fuente de Datos y Muestra**</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>La fuente de datos principal es la base de la 10ma Encuesta Nacional de Juventudes (ENJUV), realizada por el Instituto Nacional de la Juventud (INJUV) de Chile en el año 2022. Esta encuesta es representativa a nivel nacional y regional para la población de entre 15 y 29 años.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>**Operacionalización y Construcción de Variables**</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>Para abordar los objetivos del estudio, se seleccionaron y construyeron las siguientes variables clave a partir de la base de datos original:</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>**1. Variable Independiente: Situación Laboral.** Se creó una variable categórica y dicotómica a partir de las preguntas P36, P37 y P38, que indagan sobre el trabajo remunerado. Se definió como "Ocupado/a" a todo joven que respondió "1. Sí" a cualquiera de estas tres preguntas. Todos los demás casos fueron agrupados en la categoría "Desocupado/a o Inactivo/a".</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>**2. Índice de Malestar Psicológico.** Se construyó un índice sumatorio para medir sintomatología ansiosa-depresiva. Se utilizaron las variables P102_1 a P102_7, que consultan la frecuencia de sentimientos como nerviosismo, preocupación, desánimo, anhedonia, problemas de sueño, soledad e ideación suicida. Las respuestas originales en formato de texto ("Para nada", "Varios días", "Más de la mitad de los días" y "Casi todos los días") fueron recodificadas a una escala numérica del 1 al 4. El Índice de Malestar Psicológico corresponde a la suma de estos puntajes, generando un rango teórico de 7 (mínimo malestar) a 28 (máximo malestar).</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>**3. Índice de Acceso a Atención.** Para medir la percepción sobre la posibilidad de costear servicios de salud mental, se creó un segundo índice sumatorio. Se utilizaron las variables P105_1, P105_2 y P105_3, que evalúan la posibilidad de costear consultas, medicamentos y exámenes. Sus respuestas textuales ("Nada posible", "Poco posible", "Algo posible" y "Muy posible") también fueron recodificadas a una escala numérica del 1 al 4. El Índice de Acceso a Atención Psicológica es la suma de estos valores, con un rango teórico de 3 (mínimo acceso percibido) a 12 (máximo acceso percibido).</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>&nbsp;</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>**Técnicas de Análisis**</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>El flujo de trabajo analítico siguió los siguientes pasos:</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Análisis Descriptivo: Se calcularon estadísticas de tendencia central (media, mediana) y de dispersión (desviación estándar) para los dos índices construidos, agrupando los resultados por la variable de Situación Laboral para realizar una primera comparación de los grupos.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Visualización de Hallazgos: Se empleó la librería ggplot2 para generar tres tipos de visualizaciones con el fin de explorar las relaciones y distribuciones:</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Gráficos de densidad para comparar la forma completa de la distribución de ambos índices entre los dos grupos.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Diagramas de cajas (Boxplots) para obtener un resumen visual de las medianas, rangos intercuartílicos y la dispersión de los datos.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Diagrama de dispersión (Scatter plot) con líneas de tendencia por grupo, para investigar la correlación entre el malestar psicológico y el acceso percibido.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Análisis Inferencial: Se aplicaron dos tipos de pruebas de hipótesis para evaluar estadísticamente los hallazgos. Primero, para determinar si las diferencias observadas en las medias de los índices entre los grupos "Ocupado/a" y "Desocupado/a o Inactivo/a" eran significativas, se aplicó la prueba t de Student para muestras independientes, utilizando la corrección de Welch que R implementa por defecto. Segundo, para cuantificar la fuerza y dirección de la relación entre las dos variables numéricas (Índice de Malestar e Índice de Acceso), se realizó una prueba de correlación de Pearson. Para todas las pruebas se utilizó un nivel de significancia (alfa) de 0.05.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="fu">## Principales hallazgos</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Carga de librerías a utilizar</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="co"># Se carga la base de datos de la 10ma Encuesta Nacional de Juventudes y se crea un nuevo dataframe (`enjuv_procesada`) con las variables seleccionadas y transformadas.</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>enjuv <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/ENJUV_10.xlsx"</span>)</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>enjuv_procesada <span class="ot">&lt;-</span> enjuv <span class="sc">%&gt;%</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformación numérica de variables de resultado para construir indices de malestar psicológico y de acceso a atención psicológica (consultas, tratamientos y exámenes)</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="fu">across</span>(P102_1<span class="sc">:</span>P102_7, <span class="sc">~</span><span class="fu">case_when</span>(</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Para nada"</span>                   <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Varios dias"</span>                 <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Más de la mitad de los días"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Casi todos los días"</span>         <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span>                               <span class="sc">~</span> <span class="cn">NA_real_</span> </span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>  )),</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">across</span>(P105_1<span class="sc">:</span>P105_3, <span class="sc">~</span><span class="fu">case_when</span>(</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Nada posible"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Poco posible"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Algo posible"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>    . <span class="sc">==</span> <span class="st">"Muy posible"</span>  <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span>                <span class="sc">~</span> <span class="cn">NA_real_</span> </span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>  ))) <span class="sc">%&gt;%</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="co"># Creación de Índice de Malestar Psicológico y del Índice de Acceso a Atención Psicológica</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="co"># El primer índice se crea sumando las puntuaciones de las 7 preguntas P102 y el segundo se crea sumando las de las 3 preguntas P105.</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="co"># Un puntaje más alto en este índice significará un mayor malestar psicológico o mayor accesibilidad a atención psicológica.</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="co"># El rango teórico del primer índice irá de 7 (1*7, "Para nada" en todo) a 28 (4*7, "Casi todos los días" en todo). El del segundo índice irá de 3 (1*3, "Nada posible" en todo) a 12 (4*3, "Muy posible" en todo)</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>    <span class="at">indice_malestar =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., P102_1<span class="sc">:</span>P102_7), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>    <span class="at">indice_atencion =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., P105_1<span class="sc">:</span>P105_3), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Creación de la variable "Situación Laboral"</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>    <span class="at">situacion_laboral =</span> <span class="fu">if_else</span>(</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>      P36 <span class="sc">==</span> <span class="st">"1. Sí"</span> <span class="sc">|</span> P37 <span class="sc">==</span> <span class="st">"1. Sí"</span> <span class="sc">|</span> P38 <span class="sc">==</span> <span class="st">"1. Sí"</span>,</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Ocupado/a"</span>,</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Desocupado/a o Inactivo/a"</span>,</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>      <span class="at">missing =</span> <span class="st">"Desocupado/a o Inactivo/a"</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">situacion_laboral =</span> <span class="fu">as.factor</span>(situacion_laboral))</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### Análisis del Índice de Malestar Psicológico e Índice de Acceso a Atención</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tabla-descriptiva</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Estadísticas Descriptivas de los Índices por Situación Laboral"</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-pos: "H"</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: "asis"</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="co"># Creación de dataframe final solo con las columnas de interés y sin datos faltantes (na)</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>datos_analisis <span class="ot">&lt;-</span> enjuv_procesada <span class="sc">%&gt;%</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(indice_malestar, indice_atencion, situacion_laboral)</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="co"># Generación de tablas resumen</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>tabla_descriptiva <span class="ot">&lt;-</span> datos_analisis <span class="sc">%&gt;%</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(situacion_laboral) <span class="sc">%&gt;%</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>    <span class="at">Media_Malestar =</span> <span class="fu">mean</span>(indice_malestar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mediana_Malestar =</span> <span class="fu">median</span>(indice_malestar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>    <span class="at">DE_Malestar =</span> <span class="fu">sd</span>(indice_malestar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>    <span class="at">Media_Acceso =</span> <span class="fu">mean</span>(indice_atencion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mediana_Acceso =</span> <span class="fu">median</span>(indice_atencion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>    <span class="at">DE_Acceso =</span> <span class="fu">sd</span>(indice_atencion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabla_descriptiva,</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Situación Laboral"</span>, <span class="st">"N"</span>, <span class="st">"Media Malestar"</span>, <span class="st">"Mediana Malestar"</span>, <span class="st">"DE Malestar"</span>, <span class="st">"Media Acceso"</span>, <span class="st">"Mediana Acceso"</span>, <span class="st">"DE Acceso"</span>),</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">"lcccccc"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>),</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>                <span class="at">font_size =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">"6em"</span>)</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>La tabla 3.1 revela dos hallazgos centrales. Primero, en relación con el malestar psicológico, se observa que el **promedio de malestar es levemente superior en el grupo de jóvenes desocupados o inactivos** (Media = 12.1) frente a los ocupados (Media = 11.5). Sin embargo, la mediana de malestar es idéntica para ambos grupos (Mediana = 11), lo que sugiere que la diferencia en el promedio podría ser impulsada por un subconjunto de jóvenes desocupados con niveles de malestar particularmente elevados, más que por una tendencia generalizada.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>El segundo hallazgo, se refiere al acceso a la atención. Contrario a lo que se podría esperar, el **grupo de desocupados o inactivos reporta una percepción de acceso a servicios de salud mental ligeramente superior** (Media = 6.9, Mediana = 7) que el grupo de jóvenes ocupados (Media = 6.5, Mediana = 6).</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### ¿Cómo se distribuye el malestar psicológico?</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-densidad-malestar</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribución del Malestar Psicológico en Jóvenes según Situación Laboral."</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-pos: "H"</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>densidad_malestar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_analisis, <span class="fu">aes</span>(<span class="at">x =</span> indice_malestar, <span class="at">fill =</span> situacion_laboral)) <span class="sc">+</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución del Malestar Psicológico en Jóvenes"</span>,</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Según Situación Laborl (Ocupado/a vs. Desocupado/a o Inactivo/a)"</span>,</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Índice de Malestar Psicológico"</span>,</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Densidad"</span>,</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Situación Laboral"</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(densidad_malestar)</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"graficos/densidad_malestar.png"</span>, <span class="at">plot =</span> densidad_malestar, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>El gráfico de densidad (Ver Gráfico 3.1) revela que la distribución es bimodal, con un pico agudo en la zona de bajo malestar (puntaje = 8) y una meseta en la zona de malestar medio-alto.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>Al comparar los grupos se puede observar que en los niveles bajos y medios de malestar las distribuciones para jóvenes ocupados y desocupados/inactivos son notablemente similares. También se observa una diferencia clave en la cola derecha de la distribución. A partir de un puntaje de 15, el grupo de desocupados/inactivos (en rojo) presenta una densidad consistentemente mayor, lo que indica que una proporción más alta de este grupo se concentra en los niveles más elevados de malestar psicológico.</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-boxplot-malestar</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Comparación del Malestar Psicológico por Situación Laboral."</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación del malestar con un Boxplot</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>boxplot_malestar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_analisis, <span class="fu">aes</span>(<span class="at">x =</span> situacion_laboral, <span class="at">y =</span> indice_malestar, <span class="at">fill =</span> situacion_laboral)) <span class="sc">+</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Comparación del Malestar Psicológico por Situación Laboral"</span>,</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Situación Laboral"</span>,</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Índice de Malestar Psicológico"</span>,</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Situación Laboral"</span></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(boxplot_malestar)</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"graficos/boxplot_malestar.png"</span>, <span class="at">plot =</span> boxplot_malestar, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>A través del diagrama de cajas (Ver Gráfico 3.2), que compara el Índice de Malestar Psicológico entre ambos grupos, se visualiza la **identidad de las medianas**. Tanto para el grupo de jóvenes ocupados como para el de desocupados o inactivos, la mediana está en el valor 11. Esto indica que el 50% central de la muestra en ambos grupos experimenta niveles de malestar muy similares.</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>El gráfico de cajas, por lo tanto, confirma que la diferencia proviene de una mayor concentración de casos con alto malestar en la cola de la distribución del grupo de desocupados.</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="fu">### ¿Cómo se distribuye la percepción al acceso a la atencion psicológica?</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-densidad-atencion</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribución del Acceso a Atención Psicológica en Jóvenes según Situación Laboral."</span></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="co"># ¿Cómo se distribuye la percepción al acceso a la atención psicológica?</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>densidad_atencion <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_analisis, <span class="fu">aes</span>(<span class="at">x =</span> indice_atencion, <span class="at">fill =</span> situacion_laboral)) <span class="sc">+</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución del Acceso a Atención Psicológica"</span>,</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Según Situación Laboral (Ocupado/a vs. Desocupado/a o Inactivo/a)"</span>,</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Índice de Acceso a Atencion Psicológica"</span>,</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Densidad"</span>,</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Situación Laboral"</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(densidad_atencion)</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"graficos/densidad_atencion.png"</span>, <span class="at">plot =</span> densidad_atencion, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>El Gráfico 3.3 presenta la distribución del Índice de Acceso a Atención Psicológica. La distribución es marcadamente **multimodal** , con picos en los puntajes que corresponden a respuestas consistentes de "Nada posible" (3), "Poco posible" (6), "Algo posible" (9) y "Muy posible" (12).</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>La comparación entre los grupos por situación laboral revela un patrón **inverso**. En los niveles bajos de acceso percibido (picos en 3 y 6), la densidad es ligeramente mayor para el grupo de jóvenes ocupados. Por el contrario, en los niveles altos de acceso (picos en 9 y 12), la densidad del grupo de desocupados o inactivos es visiblemente superior.</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-boxplot-atencion</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Comparación del Acceso a Atención Psicológica por Situación Laboral."</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="co"># ¿Existen diferencias en la percepción de acceso a la salud mental según la situación laboral?</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>boxplot_atencion <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_analisis, <span class="fu">aes</span>(<span class="at">x =</span> situacion_laboral, <span class="at">y =</span> indice_atencion, <span class="at">fill =</span> situacion_laboral)) <span class="sc">+</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Percepción de Acceso a Atención Psicológica"</span>,</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Según Situación Laboral"</span>,</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Situación Laboral"</span>,</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Índice de Acceso (Mayor puntaje = más posible)"</span>,</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Situación Laboral"</span></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(boxplot_atencion)</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"graficos/boxplot_atencion.png"</span>, <span class="at">plot =</span> boxplot_atencion, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>El diagrama de cajas (Ver Gráfico 3.4) permite ver que la mediana del Índice de Acceso a Atención Psicológica es superior para el grupo de jóvenes desocupados o inactivos (Mediana = 7) en comparación con el grupo de jóvenes ocupados (Mediana = 6).</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>Este resultado confirma que el joven típico sin una ocupación laboral percibe que costear la atención es más posible que su contraparte empleada. Si bien el rango de respuestas es similar para ambos grupos, la tendencia central está claramente desplazada.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="fu">### ¿Cuál es la relación entre el malestar psicológico y el acceso percibido?</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-diagrama-indices</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Relación entre el malestar psicológico y el acceso percibido."</span></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="co"># ¿Cuál es la relación entre el malestar psicológico y el acceso percibido?</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>diagrama_indices <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_analisis, <span class="fu">aes</span>(<span class="at">x =</span> indice_malestar, <span class="at">y =</span> indice_atencion, <span class="at">color =</span> situacion_laboral)) <span class="sc">+</span></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">height =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relación entre Malestar Psicológico y Acceso a Atención"</span>,</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Índice de Malestar Psicológico"</span>,</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Índice de Acceso Percibido"</span>,</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Situación Laboral"</span></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(diagrama_indices)</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"graficos/diagrama_indices.png"</span>, <span class="at">plot =</span> diagrama_indices, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>)</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>Finalmente, para explorar la interacción entre el malestar y el acceso, se generó un diagrama de dispersión con líneas de tendencia por grupo (Ver Gráfico 3.5). Este gráfico revela dos patrones significativos.</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>Primero, se observa una correlación positiva entre el malestar psicológico y el acceso percibido para ambos grupos. Las líneas de tendencia ascendentes indican que los jóvenes que reportan un mayor malestar también tienden a reportar una mayor posibilidad de costear la atención.</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>Segundo, el gráfico confirma que existe una brecha sistemática entre los grupos. Para cualquier nivel de malestar, la línea de tendencia del grupo de desocupados/inactivos se sitúa por encima de la del grupo de ocupados, reafirmando que su percepción de acceso es consistentemente superior.</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="fu">### Análisis Inferencial</span></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tabla-ttest</span></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Resultados de las Pruebas t de Student para la Diferencia de Medias.\nNota: gl = Grados de Libertad; IC = Intervalo de Confianza."</span></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar las pruebas t y guardar los resultados</span></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>test_malestar <span class="ot">&lt;-</span> <span class="fu">t.test</span>(indice_malestar <span class="sc">~</span> situacion_laboral, <span class="at">data =</span> datos_analisis)</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>test_atencion <span class="ot">&lt;-</span> <span class="fu">t.test</span>(indice_atencion <span class="sc">~</span> situacion_laboral, <span class="at">data =</span> datos_analisis)</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un dataframe con los resultados</span></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>tabla_resultados_t <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>  <span class="at">Indice =</span> <span class="fu">c</span>(<span class="st">"Malestar Psicológico"</span>, <span class="st">"Acceso a Atención"</span>),</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Combinamos el estadístico t y los grados de libertad (gl) en una sola columna</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>  <span class="co"># sprintf() para formatear los números</span></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a>  <span class="at">t_stat_df =</span> <span class="fu">c</span>(</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.2f (%.2f)"</span>, test_malestar<span class="sc">$</span>statistic, test_malestar<span class="sc">$</span>parameter),</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.2f (%.2f)"</span>, test_atencion<span class="sc">$</span>statistic, test_atencion<span class="sc">$</span>parameter)</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Formatear el valor p en notación científica</span></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>  <span class="at">valor_p =</span> <span class="fu">c</span>(</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>    <span class="fu">format</span>(test_malestar<span class="sc">$</span>p.value, <span class="at">scientific =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>),</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>    <span class="fu">format</span>(test_atencion<span class="sc">$</span>p.value, <span class="at">scientific =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Unificar intervalo de confianza en una sola columna [Lím. Inf, Lím. Sup]</span></span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>  <span class="at">ic_95 =</span> <span class="fu">c</span>(</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"[%.2f, %.2f]"</span>, test_malestar<span class="sc">$</span>conf.int[<span class="dv">1</span>], test_malestar<span class="sc">$</span>conf.int[<span class="dv">2</span>]),</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"[%.2f, %.2f]"</span>, test_atencion<span class="sc">$</span>conf.int[<span class="dv">1</span>], test_atencion<span class="sc">$</span>conf.int[<span class="dv">2</span>])</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir nombres de las columnas para la tabla final</span></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a>nombres_columnas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Índice Analizado"</span>,</span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Estadístico t (gl)"</span>,</span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Valor p"</span>,</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>  <span class="st">"IC 95% para la Diferencia"</span></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla final</span></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabla_resultados_t, <span class="at">col.names =</span> nombres_columnas, <span class="at">align =</span> <span class="st">"lccc"</span>, ) <span class="sc">%&gt;%</span></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>), <span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">"15em"</span>)</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>Como se observa en la Tabla 3.2, los resultados de las pruebas t de Student confirman que las diferencias observadas entre los grupos "Ocupado/a" y "Desocupado/a o Inactivo/a" son estadísticamente significativas para ambos índices.</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>Para el Índice de Malestar Psicológico, el valor p (p <span class="sc">\&lt;</span> .001) nos permite rechazar la hipótesis nula, confirmando que los jóvenes sin ocupación laboral presentan, en promedio, un malestar mayor. De manera aún más marcada, la prueba para el Índice de Acceso a Atención también arroja un resultado altamente significativo (p <span class="sc">\&lt;</span> .001), validando estadísticamente el hallazgo paradójico de que el grupo de desocupados/inactivos reporta una percepción de acceso superior.</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: test-correlacion</span></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Prueba de Correlación de Pearson entre Malestar Psicológico y Acceso a Atención"</span></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-pos: "H"</span></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a>test_correlacion <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="sc">~</span> indice_malestar <span class="sc">+</span> indice_atencion, <span class="at">data =</span> datos_analisis)</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>tabla_cor <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"Malestar Psicológico y Acceso a Atención"</span>,</span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a>  <span class="at">coeficiente_r =</span> test_correlacion<span class="sc">$</span>estimate[[<span class="dv">1</span>]],</span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>  <span class="at">grados_libertad =</span> <span class="fu">round</span>(test_correlacion<span class="sc">$</span>parameter[[<span class="dv">1</span>]]),</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a>  <span class="at">valor_p =</span> <span class="fu">ifelse</span>(test_correlacion<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"&lt; .001"</span>, <span class="fu">round</span>(test_correlacion<span class="sc">$</span>p.value, <span class="dv">3</span>))</span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>nombres_de_columna <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Variables Analizadas"</span>,</span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Coeficiente de Correlación (r)"</span>,</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Grados de Libertad (gl)"</span>,</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Valor p"</span></span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a>  tabla_cor,</span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> nombres_de_columna,</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">"lccc"</span></span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a>A su vez, para cuantificar la relación observada en el diagrama de dispersión entre el malestar psicológico y el acceso percibido, se realizó una prueba de correlación de Pearson.</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a>Los resultados revelan una correlación positiva, aunque moderada, que es estadísticamente muy significativa (cor = .31, p <span class="sc">\&lt;</span> .001). Esto indica que a medida que aumenta el Índice de Malestar Psicológico, también tiende a aumentar el Índice de Acceso a Atención. El hallazgo respalda la hipótesis de que la necesidad de atención puede generar una mayor conciencia de las vías de acceso disponibles.</span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusiones</span></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a>El presente análisis sobre la relación entre situación laboral y salud mental en las juventudes chilenas, basado en la 10ma ENJUV, revela un panorama complejo y lleno de matices. Si bien se confirma que el grupo "Desocupado/a" presentan mayores indices de malestar psicológico, los hallazgos en torno al acceso a la atención y la interacción entre variables pintan un cuadro que requiere una interpretación crítica.</span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>En primer lugar, el análisis corrobora que la falta de ocupación laboral está asociada a un mayor detrimento de la salud mental. Aunque la experiencia de malestar más común es similar para todos los jóvenes, la vulnerabilidad a sufrir niveles de angustia más severos es significativamente mayor en el grupo que no tiene una ocupación. Como demostró el análisis de distribución, es esta mayor concentración de casos en los extremos más agudos del malestar lo que impulsa la diferencia estadísticamente significativa entre las medias, confirmando que la inactividad o el desempleo representan un factor de riesgo para el bienestar psicológico.</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a>Sin embargo, el hallazgo más interesante surge al analizar la percepción de acceso a la atención. Contrario a lo que se podría esperar, tener un empleo no se traduce en una mejor percepción de acceso a los servicios de salud mental; de hecho, la tendencia es significativamente opuesta. Esta aparente contradicción podría explicarse por la precariedad del mercado laboral juvenil. Es plausible que muchos empleos ofrezcan bajos salarios y carezcan de seguros de salud robustos, generando una percepción de que los ingresos son insuficientes para costear un tratamiento. Por otro lado, jóvenes inactivos (como estudiantes) o desocupados podrían tener mayor conciencia de su cobertura a través de sistemas públicos como FONASA o de seguros familiares, lo que, a pesar de otras barreras, eleva su percepción de poder acceder a atenderse.</span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a>Finalmente, el análisis de la relación directa entre malestar y acceso añade una capa más de complejidad, mostrando una correlación positiva: a mayor malestar, mayor es el acceso percibido. Esto sugiere que la propia necesidad de atención podría actuar como un motor para que los jóvenes tomen conciencia de las vías de acceso que, de otro modo, no habrían explorado.</span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>En resumen, este trabajo concluye que, si bien la falta de ocupación es un factor de vulnerabilidad para la salud mental, el mero hecho de tener un empleo no garantiza ni el bienestar ni el acceso a los medios para procurarlo. Las condiciones de la empleabilidad juvenil emergen como un factor crítico que merece un análisis más profundo, sugiriendo que las políticas públicas deben enfocarse no solo en la creación de puestos de trabajo, sino también en la calidad y la seguridad que estos ofrecen para asegurar un desarrollo integral de las juventudes.</span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fuentes consultadas</span></span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>Instituto Nacional de la Juventud (INJUV). (2022). 10ma Encuesta Nacional de Juventudes. Santiago, Chile. <span class="ot">&lt;https://www.injuv.gob.cl/encuestanacionaldejuventud&gt;</span>.</span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>Fundación SOL. (2025). Escuela de Datos 2025. <span class="ot">&lt;https://aulavirtual.escuelasol.cl/escuela-de-datos&gt;</span></span>
</code><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>